import type { InterviewArea, InterviewPlan } from './types';

/**
 * Role-aware interview agendas.
 *
 * Every session walks an ordered list of competency areas rather than asking
 * scattered questions. A fullstack candidate gets language → frontend → backend
 * → database → API integration; an AI engineer or an HR candidate gets a
 * completely different flow.
 *
 * A per-candidate plan is normally generated from their resume (see
 * `buildPlanPrompt` + /api/summarize-profile). This library is the deterministic
 * fallback for when no AI provider is configured or the model returns garbage,
 * and it anchors what a good plan looks like for each role family.
 */

export const MIN_AREAS = 3;
export const MAX_AREAS = 6;

/** [key, title, focus, probes] — compact so the table below stays readable. */
type AreaSpec = [string, string, string, string[]];

function plan(roleFamily: string, specs: AreaSpec[]): InterviewPlan {
  return {
    roleFamily,
    areas: specs.map(([key, title, focus, probes]) => ({ key, title, focus, probes })),
  };
}

type RoleKey =
  // --- Engineering / build ---
  | 'fullstack' | 'frontend' | 'backend' | 'mobile-android' | 'mobile-ios'
  | 'embedded' | 'game-dev' | 'blockchain' | 'salesforce-developer'
  // --- Data / AI ---
  | 'ai-engineer' | 'data-scientist' | 'data-analyst' | 'data-engineer'
  | 'mlops' | 'computer-vision' | 'nlp' | 'bi-developer' | 'prompt-engineer'
  // --- Infrastructure / operations ---
  | 'devops' | 'sre' | 'cloud-architect' | 'platform-engineer'
  | 'network-engineer' | 'dba' | 'security'
  // --- Quality / architecture / leadership ---
  | 'qa-sdet' | 'solutions-architect' | 'engineering-manager'
  | 'technical-pm' | 'support-engineer' | 'ux-designer'
  // --- Non-technical ---
  | 'hr' | 'business-development' | 'sales' | 'product' | 'marketing'
  | 'finance' | 'support' | 'generic';

const PLANS: Record<RoleKey, InterviewPlan> = {
  // =========================================================================
  // Engineering / build
  // =========================================================================
  fullstack: plan('Fullstack Developer', [
    ['language', 'Programming language',
      'Core language fundamentals for the stack on the resume — typing, async model, scope/memory, error handling, and idiomatic patterns.',
      ['Walk me through what actually happens when an async call in your main language hits an unhandled rejection.',
       'Where does your language surprise people who came from another one?',
       'Show me a pattern you use constantly and tell me what it costs you.']],
    ['frontend', 'Frontend',
      'Component architecture, state management, rendering and data-fetching strategy, accessibility, and browser performance.',
      ['How do you decide what state lives in a component versus a store versus the server?',
       'What made your slowest page slow, and how did you prove it?',
       'How do you keep a form accessible once it has conditional fields?']],
    ['backend', 'Backend',
      'Service structure, request lifecycle, auth, caching, background jobs, and reasoning about failure under load.',
      ['Take one endpoint you built and trace the request end to end.',
       'What did you cache, and how did you invalidate it?',
       'What breaks first when traffic multiplies by ten?']],
    ['database', 'Database',
      'Schema and data modelling, indexing, query performance, transactions, migrations, and SQL vs NoSQL trade-offs.',
      ['Describe a schema you designed and what you would change now.',
       'How did you diagnose a slow query, and what did the plan tell you?',
       'How do you ship a migration on a table that is being written to?']],
    ['api-integration', 'API integration',
      'API contracts, versioning, pagination, idempotency, retries and timeouts, webhooks, and third-party failure handling.',
      ['How do you make a payment or write call safe to retry?',
       'A third-party API starts timing out intermittently — what do you do?',
       'How did you version an API without breaking existing clients?']],
  ]),

  frontend: plan('Frontend Engineer', [
    ['language', 'Language fundamentals',
      'JavaScript/TypeScript depth — closures, the event loop, async patterns, typing discipline, immutability.',
      ['Explain the event loop using a bug you actually hit.',
       'When do generics genuinely earn their complexity in your TypeScript?',
       'What is the difference between a microtask and a macrotask in practice?']],
    ['framework', 'Framework & components',
      'Component design, lifecycle/hooks, reuse, and rendering strategy in the framework on their resume.',
      ['How do you decide a component needs to be split?',
       'Describe a re-render problem you tracked down.',
       'When do you reach for context, and when is it the wrong tool?']],
    ['state-data', 'State & data',
      'Client vs server state, caching and invalidation, data fetching, optimistic updates, forms and validation.',
      ['How do you handle an optimistic update that fails server-side?',
       'What is your cache invalidation strategy for list-plus-detail views?',
       'Where do you validate — client, server, or both, and why?']],
    ['performance-a11y', 'Performance & accessibility',
      'Bundle size, Core Web Vitals, rendering cost, semantic markup, keyboard navigation, ARIA.',
      ['Which metric did you move, and by how much?',
       'How do you keep a custom dropdown keyboard-usable?',
       'What is in your bundle that should not be?']],
    ['testing-tooling', 'Testing & tooling',
      'Unit/integration/E2E strategy, build tooling, and how a change ships safely.',
      ['What do you refuse to unit test, and why?',
       'How do you stop E2E tests going flaky?',
       'Walk me through your build pipeline from commit to production.']],
  ]),

  backend: plan('Backend Engineer', [
    ['language', 'Programming language',
      'Language internals for their stack — concurrency model, memory, error handling, idiomatic design.',
      ['How does concurrency actually work in your language of choice?',
       'How do you handle errors you cannot recover from?',
       'What is the most expensive language-level mistake you have made?']],
    ['api-design', 'API design',
      'Contract design, versioning, idempotency, pagination, auth, backwards compatibility.',
      ['How do you design an endpoint that may return a million rows?',
       'What makes an API contract hard to change later?',
       'How do you authenticate service-to-service calls?']],
    ['database', 'Database & data modelling',
      'Schema design, indexing, query plans, transactions, consistency trade-offs.',
      ['When did a normalised schema hurt you?',
       'Explain an isolation-level problem you have actually hit.',
       'Which index did you add, and how did you confirm it helped?']],
    ['scalability', 'Scalability & reliability',
      'Caching, queues, horizontal scaling, failure modes, retries and backoff, observability, incidents.',
      ['What was your worst outage and what was the real root cause?',
       'How do you prevent a retry storm?',
       'What do you put in a queue, and what do you never put in one?']],
    ['security', 'Security',
      'AuthN/AuthZ, secret handling, input validation, common injection and exposure classes.',
      ['How do you store and rotate credentials?',
       'How would you review your own code for authorisation bugs?',
       'Where does your system trust input it should not?']],
  ]),

  'mobile-android': plan('Android Engineer', [
    ['kotlin', 'Kotlin & platform',
      'Kotlin depth, coroutines and structured concurrency, Android lifecycle and process death.',
      ['How do you survive process death without losing user input?',
       'Explain a coroutine scope leak you have fixed.',
       'What actually happens on configuration change?']],
    ['ui-state', 'UI & state',
      'Compose or Views, navigation, state hoisting, and configuration handling.',
      ['How do you structure state in Compose for a complex screen?',
       'How do you handle back-stack state across deep links?',
       'What recomposition problem cost you the most time?']],
    ['data-offline', 'Data & offline',
      'Room/persistence, sync and conflict resolution, network resilience.',
      ['How do you reconcile a local edit with a stale server record?',
       'What does your app do on a flaky 2G connection?',
       'How do you test offline behaviour?']],
    ['performance', 'Performance',
      'Startup time, memory, jank profiling, battery, APK size.',
      ['How did you measure and cut cold-start time?',
       'How do you find the source of dropped frames?',
       'What is the biggest thing in your APK?']],
    ['release', 'Release & quality',
      'Play Store release process, crash monitoring, staged rollout, testing strategy.',
      ['How do you decide to halt a staged rollout?',
       'What is in your pre-release checklist?',
       'How do you triage a crash you cannot reproduce?']],
  ]),

  'mobile-ios': plan('iOS Engineer', [
    ['swift', 'Swift & platform',
      'Swift depth, value vs reference semantics, ARC and retain cycles, concurrency.',
      ['Where have you hit a retain cycle, and how did you find it?',
       'When do you choose a struct over a class, concretely?',
       'How does Swift concurrency change how you write networking code?']],
    ['ui-state', 'UI & state',
      'SwiftUI or UIKit, navigation, state management, layout across device classes.',
      ['How do you manage shared state across a SwiftUI navigation stack?',
       'What SwiftUI limitation forced you back to UIKit?',
       'How do you handle dynamic type and larger accessibility sizes?']],
    ['data-offline', 'Data & offline',
      'Core Data/persistence, sync, background refresh, network resilience.',
      ['How do you resolve a sync conflict in Core Data?',
       'What runs in a background task, and what are its limits?',
       'How do you migrate a persistent store safely?']],
    ['performance', 'Performance',
      'Launch time, memory, scrolling performance, Instruments usage, binary size.',
      ['Walk me through profiling a stutter in Instruments.',
       'How did you reduce launch time?',
       'What causes memory growth in your app over a long session?']],
    ['release', 'Release & quality',
      'App Store review, TestFlight, crash monitoring, phased release, testing strategy.',
      ['How do you handle an App Store rejection under deadline?',
       'What do you gate behind a feature flag?',
       'How do you test push notifications properly?']],
  ]),

  embedded: plan('Embedded / Firmware Engineer', [
    ['c-systems', 'C & systems fundamentals',
      'Pointers, memory layout, volatile/const correctness, undefined behaviour, and toolchain awareness.',
      ['When do you actually need volatile?',
       'Describe a memory corruption bug you tracked down.',
       'What does your linker script control?']],
    ['rtos', 'RTOS & concurrency',
      'Task scheduling, priorities, ISRs, race conditions, priority inversion, watchdogs.',
      ['What can and cannot happen inside an ISR?',
       'Describe a priority inversion you have seen.',
       'How do you make a shared buffer safe between an ISR and a task?']],
    ['hardware', 'Hardware interfaces',
      'I2C/SPI/UART, GPIO, DMA, timers, datasheet reading, and signal debugging.',
      ['Your I2C bus is hanging — how do you debug it?',
       'When would you use DMA over an interrupt-driven read?',
       'Walk me through bringing up a new peripheral from its datasheet.']],
    ['constraints', 'Power & constraints',
      'Power modes, memory and flash budgets, real-time deadlines, and optimisation trade-offs.',
      ['How did you cut power consumption on a battery device?',
       'What did you sacrifice to fit in flash?',
       'How do you guarantee a hard real-time deadline?']],
    ['test-release', 'Testing & field release',
      'Hardware-in-the-loop testing, OTA/firmware update safety, and field failure diagnosis.',
      ['How do you make an OTA update non-bricking?',
       'How do you test firmware without the hardware in front of you?',
       'How do you diagnose a failure that only happens in the field?']],
  ]),

  'game-dev': plan('Game Developer', [
    ['engine', 'Engine & language',
      'Unity/Unreal/custom engine depth, C++/C# performance patterns, and engine lifecycle.',
      ['What does the engine do between your frames?',
       'Where do you avoid allocations, and why?',
       'What engine limitation have you had to work around?']],
    ['gameplay', 'Gameplay systems',
      'Game loop, state machines, physics, input handling, and system architecture.',
      ['How do you structure a character state machine that stays maintainable?',
       'How do you decouple gameplay systems from each other?',
       'Fixed vs variable timestep — what did you choose and why?']],
    ['graphics', 'Graphics & rendering',
      'Render pipeline, shaders, draw-call batching, LOD, and lighting cost.',
      ['How do you cut draw calls in a dense scene?',
       'Explain a shader you wrote and what it cost.',
       'How do you budget a frame?']],
    ['performance', 'Performance & memory',
      'Profiling, frame budgets, GC pressure, asset streaming, and platform targets.',
      ['How did you hit your frame budget on the weakest target platform?',
       'How do you handle GC spikes?',
       'What is your asset streaming strategy?']],
    ['production', 'Production & polish',
      'Build pipeline, multiplayer/netcode if claimed, playtesting, and shipping under deadline.',
      ['How do you handle latency in your netcode?',
       'What did playtesting change about your design?',
       'What did you cut to ship?']],
  ]),

  blockchain: plan('Blockchain Engineer', [
    ['fundamentals', 'Protocol fundamentals',
      'Consensus, finality, gas/fee mechanics, and the actual guarantees a chain gives.',
      ['What does finality mean on the chain you worked with?',
       'Why is block reordering a problem for your application?',
       'Where does your app rely on a trust assumption you cannot enforce?']],
    ['smart-contracts', 'Smart contracts',
      'Solidity/Rust contract design, storage layout, upgradeability, and gas optimisation.',
      ['How did you make a contract upgradeable, and what did it risk?',
       'Where did you optimise gas and what did it cost in readability?',
       'How do you handle a failed external call?']],
    ['security', 'Contract security',
      'Reentrancy, oracle manipulation, access control, integer issues, and audit process.',
      ['Walk me through a reentrancy vector and its fix.',
       'How do you protect against oracle price manipulation?',
       'What did your last audit find?']],
    ['integration', 'Off-chain integration',
      'Indexing, event handling, wallet integration, RPC reliability, and reorg handling.',
      ['How do you handle a chain reorg in your indexer?',
       'What happens when your RPC provider degrades?',
       'How do you present a pending transaction honestly to users?']],
    ['testing', 'Testing & deployment',
      'Fork testing, invariant/fuzz testing, testnet process, and deployment safety.',
      ['How do you test against real mainnet state?',
       'What invariants do you fuzz?',
       'What is your deployment checklist for an immutable contract?']],
  ]),

  'salesforce-developer': plan('Salesforce / CRM Developer', [
    ['platform', 'Platform fundamentals',
      'Objects, relationships, governor limits, and declarative vs programmatic decisions.',
      ['When do you build with clicks rather than code?',
       'Which governor limit has actually bitten you?',
       'How do you model a many-to-many relationship?']],
    ['apex', 'Apex & triggers',
      'Trigger frameworks, bulkification, async Apex, and test coverage.',
      ['How do you keep a trigger bulk-safe?',
       'One-trigger-per-object — do you follow it, and why?',
       'When do you use Queueable over Batch?']],
    ['ui', 'Lightning & UI',
      'LWC architecture, component communication, and page performance.',
      ['How do two sibling LWCs communicate?',
       'What makes a Lightning page slow?',
       'How do you handle errors visibly to the user?']],
    ['integration', 'Integrations',
      'REST/SOAP callouts, middleware, external objects, and error/retry handling.',
      ['How do you handle a callout that fails mid-transaction?',
       'How do you sync Salesforce with an external system of record?',
       'What did you do about duplicate records?']],
    ['release', 'Release & data',
      'Sandboxes, deployment (change sets, SFDX), data migration, and permissions.',
      ['Walk me through your deployment process.',
       'How do you migrate data without breaking references?',
       'How do you audit who can see what?']],
  ]),

  // =========================================================================
  // Data / AI
  // =========================================================================
  'ai-engineer': plan('AI / ML Engineer', [
    ['ml-fundamentals', 'ML fundamentals',
      'Bias/variance, over- and under-fitting, loss functions, regularisation, and when a classical model beats a neural one.',
      ['When did a simpler model beat your neural network?',
       'How do you detect overfitting before production does?',
       'Why did you pick that loss function?']],
    ['data-pipeline', 'Data & features',
      'Data sourcing and labelling, leakage, class imbalance, feature engineering, train/serve skew.',
      ['Where could label leakage have crept into your training set?',
       'How did you handle severe class imbalance?',
       'How do you guarantee the features at serving match training?']],
    ['training-eval', 'Training & evaluation',
      'Experiment design, metric selection beyond accuracy, offline vs online evaluation.',
      ['Accuracy went up but the product got worse — what happened?',
       'What is your offline metric and why does it correlate with the business one?',
       'How do you decide a model is ready to ship?']],
    ['llm-systems', 'LLM systems',
      'Prompting, RAG architecture, embeddings and retrieval quality, tool calling, generative evaluation, hallucination mitigation.',
      ['Your RAG system returns confident nonsense — how do you debug it?',
       'How do you evaluate a generative output without a ground-truth label?',
       'What did you chunk, and how did chunking change retrieval quality?']],
    ['deployment', 'Deployment & MLOps',
      'Serving architecture, latency and cost, versioning, drift monitoring, rollback.',
      ['How do you detect drift in production?',
       'What does inference cost you per request, and how did you cut it?',
       'How do you roll back a bad model safely?']],
  ]),

  'data-scientist': plan('Data Scientist', [
    ['statistics', 'Statistics',
      'Hypothesis testing, significance and power, confounders, causal reasoning.',
      ['Your test is significant at n=40 — do you trust it?',
       'How do you tell correlation from causation in your own analysis?',
       'What is a confounder you missed and later found?']],
    ['modelling', 'Modelling',
      'Model selection, validation strategy, feature engineering, and interpretability.',
      ['How do you set up cross-validation with time-series data?',
       'How do you explain a model to a stakeholder who distrusts it?',
       'When do you choose interpretability over accuracy?']],
    ['experimentation', 'Experimentation',
      'A/B test design, sample sizing, guardrail metrics, and reading an ambiguous result.',
      ['How do you size an experiment before running it?',
       'The primary metric is flat but a guardrail moved — now what?',
       'How do you handle peeking at results early?']],
    ['data-wrangling', 'Data wrangling',
      'SQL depth, Python/pandas workflow, data quality, and reproducibility.',
      ['Write me the logic for a retention cohort query.',
       'How do you make an analysis reproducible six months later?',
       'What do you do about missing data?']],
    ['communication', 'Business impact',
      'Framing an ambiguous question, and communicating findings to non-technical stakeholders.',
      ['Tell me about an analysis that changed a decision.',
       'How do you present uncertainty without losing the room?',
       'When have you told a stakeholder the data does not support their idea?']],
  ]),

  'data-analyst': plan('Data Analyst', [
    ['sql', 'SQL',
      'Joins, window functions, aggregation, CTEs, and query performance.',
      ['How would you find each user’s second purchase using window functions?',
       'What is the difference between a LEFT JOIN filter in WHERE versus ON?',
       'How do you speed up a query over a huge fact table?']],
    ['modelling', 'Data modelling',
      'Star schemas, grain, joins across sources, and metric definitions.',
      ['What is the grain of your main fact table?',
       'Two dashboards disagree on revenue — how do you resolve it?',
       'How do you define an "active user" defensibly?']],
    ['visualisation', 'Visualisation & reporting',
      'Dashboard design, chart choice, and building something people actually use.',
      ['What makes a dashboard get ignored?',
       'When is a table better than a chart?',
       'How do you handle a stakeholder demanding a vanity metric?']],
    ['statistics', 'Analytical rigour',
      'Basic inference, seasonality, sample bias, and sanity-checking a number.',
      ['A metric jumped 30% overnight — walk me through your checks.',
       'How do you separate seasonality from a real trend?',
       'How do you know your data is not simply wrong?']],
    ['impact', 'Business impact',
      'Turning a vague request into a question, and driving a decision.',
      ['Tell me about a recommendation that was acted on.',
       'How do you push back on a badly framed request?',
       'What did you stop reporting, and why?']],
  ]),

  'data-engineer': plan('Data Engineer', [
    ['pipelines', 'Pipeline design',
      'Batch vs streaming, orchestration, idempotency, backfills, and dependency management.',
      ['How do you make a pipeline safe to re-run?',
       'How do you backfill two years of data without melting the warehouse?',
       'Batch or streaming for this use case — and why?']],
    ['modelling', 'Storage & modelling',
      'Warehouse/lake design, partitioning, file formats, and schema evolution.',
      ['How do you partition a table that is queried by two different keys?',
       'How do you evolve a schema without breaking consumers?',
       'Parquet vs row formats — when does it matter?']],
    ['processing', 'Processing at scale',
      'Spark/SQL engine internals, skew, shuffles, and cost/performance tuning.',
      ['How do you diagnose and fix data skew?',
       'What causes an expensive shuffle and how do you avoid one?',
       'How did you cut compute cost on a heavy job?']],
    ['quality', 'Data quality & reliability',
      'Testing, contracts, freshness SLAs, lineage, and on-call for data.',
      ['How do you catch a silent data-quality regression?',
       'What is in your data contract with upstream teams?',
       'A dashboard is stale at 9am — walk me through your response.']],
    ['governance', 'Governance & access',
      'PII handling, access control, retention, and cost governance.',
      ['How do you handle PII across environments?',
       'How do you stop warehouse costs running away?',
       'Who can query raw data, and why?']],
  ]),

  mlops: plan('MLOps Engineer', [
    ['pipelines', 'Training pipelines',
      'Reproducible training, data/model versioning, orchestration, and experiment tracking.',
      ['How do you reproduce a model trained six months ago?',
       'What do you version besides the model weights?',
       'How is a retrain triggered?']],
    ['serving', 'Model serving',
      'Inference architecture, batching, latency/throughput, GPU utilisation, and cost.',
      ['How do you hit a p99 latency target on GPU inference?',
       'When do you batch, and what does it cost in latency?',
       'How do you scale to zero without cold-start pain?']],
    ['monitoring', 'Monitoring & drift',
      'Data and prediction drift, performance decay, alerting, and feedback loops.',
      ['How do you detect drift without ground-truth labels?',
       'What alerts on a model, and who gets paged?',
       'How do you close the feedback loop from production back into training?']],
    ['release', 'Release & rollback',
      'Shadow deploys, canaries, A/B rollout of models, and rollback safety.',
      ['How do you validate a model in production before it serves traffic?',
       'What triggers an automatic rollback?',
       'How do you compare two models fairly online?']],
    ['infrastructure', 'Infrastructure & cost',
      'Containers, GPU scheduling, IaC, CI/CD for ML, and spend control.',
      ['How do you schedule scarce GPUs across teams?',
       'What does CI look like for a model repo?',
       'Where did you cut the most cost?']],
  ]),

  'computer-vision': plan('Computer Vision Engineer', [
    ['fundamentals', 'CV fundamentals',
      'Convolutions, augmentation, transfer learning, and classical CV where it still wins.',
      ['When is classical CV still the right answer?',
       'Which augmentations actually helped, and how did you know?',
       'How do you choose a backbone?']],
    ['data', 'Data & annotation',
      'Dataset construction, labelling quality, class imbalance, and domain gap.',
      ['How did you handle inconsistent annotations?',
       'What is the domain gap between your training data and production?',
       'How much data was actually enough?']],
    ['training', 'Training & evaluation',
      'Loss design, mAP/IoU and task-appropriate metrics, and error analysis.',
      ['Explain mAP to me and what it hides.',
       'How do you do error analysis on detections?',
       'Your model fails on one camera angle — what now?']],
    ['deployment', 'Deployment & optimisation',
      'Quantisation, pruning, TensorRT/ONNX, edge constraints, and real-time budgets.',
      ['How did you get inference under the frame budget?',
       'What did quantisation cost you in accuracy?',
       'How do you run this on an edge device?']],
    ['production', 'Production behaviour',
      'Lighting/occlusion robustness, monitoring, and failure handling in the real world.',
      ['What happens in bad lighting?',
       'How do you monitor a vision model in production?',
       'What is your fallback when confidence is low?']],
  ]),

  nlp: plan('NLP Engineer', [
    ['fundamentals', 'NLP fundamentals',
      'Tokenisation, embeddings, attention, and classical NLP where appropriate.',
      ['What does your tokeniser do to domain jargon?',
       'When is a simple classifier better than a transformer here?',
       'Explain attention in terms of a problem you solved with it.']],
    ['data', 'Data & preprocessing',
      'Corpus construction, annotation, imbalance, multilinguality, and noise.',
      ['How did you clean a noisy real-world text corpus?',
       'How do you handle multiple languages in one pipeline?',
       'How did you measure annotation agreement?']],
    ['modelling', 'Modelling & fine-tuning',
      'Fine-tuning vs prompting, LoRA/PEFT, and task framing.',
      ['When do you fine-tune instead of prompt?',
       'What did you actually fine-tune, and on how much data?',
       'How do you frame a fuzzy business task as an NLP task?']],
    ['evaluation', 'Evaluation',
      'Task metrics, human evaluation, generative evaluation, and benchmark limitations.',
      ['How do you evaluate a summary?',
       'Where did a benchmark mislead you?',
       'How do you set up human evaluation cheaply?']],
    ['production', 'Production systems',
      'Latency, cost, retrieval, safety filtering, and monitoring language output.',
      ['How do you keep generation cost sane at scale?',
       'How do you filter unsafe or off-brand output?',
       'How do you monitor quality drift in generated text?']],
  ]),

  'bi-developer': plan('BI Developer', [
    ['modelling', 'Semantic modelling',
      'Star schema design, measures, grain, and single-source-of-truth metric definitions.',
      ['How do you stop two reports disagreeing on the same metric?',
       'How do you handle slowly changing dimensions?',
       'What lives in the semantic layer versus the warehouse?']],
    ['tooling', 'BI tooling',
      'Power BI/Tableau/Looker depth — DAX/LookML, extracts vs live, and refresh strategy.',
      ['Explain a DAX or LookML expression you are proud of.',
       'Live connection or extract — how do you decide?',
       'How do you handle row-level security?']],
    ['performance', 'Report performance',
      'Query cost, aggregation strategy, caching, and dashboard responsiveness.',
      ['A dashboard takes 40 seconds to load — what do you check?',
       'How do you use aggregate tables effectively?',
       'What is your caching strategy?']],
    ['design', 'Dashboard design',
      'Audience-appropriate design, chart selection, and drill paths.',
      ['How do you design for an executive versus an analyst?',
       'What did you remove from a dashboard and why?',
       'How do you support drill-down without clutter?']],
    ['governance', 'Governance & adoption',
      'Certification, documentation, access control, and driving actual usage.',
      ['How do you know a report is being used?',
       'How do you retire a report people still ask for?',
       'How do you certify a metric definition?']],
  ]),

  'prompt-engineer': plan('AI Application / Prompt Engineer', [
    ['prompting', 'Prompt design',
      'Instruction design, few-shot strategy, structured output, and failure-mode reduction.',
      ['How do you force reliable structured output?',
       'What does a failing prompt look like before it fails loudly?',
       'When do few-shot examples hurt?']],
    ['rag', 'Retrieval & context',
      'Chunking, embedding choice, retrieval quality, reranking, and context budgeting.',
      ['How did you decide your chunk size?',
       'How do you tell a retrieval failure from a generation failure?',
       'What goes in the context window when it does not all fit?']],
    ['agents', 'Tools & agents',
      'Tool/function calling, orchestration, error recovery, and bounding autonomy.',
      ['How do you stop an agent looping forever?',
       'How do you design a tool schema the model uses correctly?',
       'What do you never let the model do without a human?']],
    ['evaluation', 'Evaluation',
      'Eval sets, LLM-as-judge and its limits, regression testing of prompts.',
      ['How do you regression-test a prompt change?',
       'Where does LLM-as-judge mislead you?',
       'What is in your eval set, and how did you build it?']],
    ['production', 'Production concerns',
      'Latency, cost, caching, safety, prompt injection, and monitoring.',
      ['How do you defend against prompt injection from retrieved content?',
       'How did you cut token cost without losing quality?',
       'What do you log, given the content may be sensitive?']],
  ]),

  // =========================================================================
  // Infrastructure / operations
  // =========================================================================
  devops: plan('DevOps Engineer', [
    ['linux-networking', 'Linux & networking',
      'Processes, filesystems, DNS, TLS, load balancing, and debugging a live host.',
      ['A host is at 100% CPU — walk me through your first five commands.',
       'Explain what happens in a TLS handshake that can fail.',
       'How do you debug a DNS problem you cannot reproduce locally?']],
    ['ci-cd', 'CI/CD',
      'Pipeline design, artefact promotion, deployment strategies, and rollback.',
      ['How does an artefact move from dev to production in your pipeline?',
       'Blue/green or rolling — what did you choose and why?',
       'How fast can you roll back, honestly?']],
    ['cloud-iac', 'Cloud & IaC',
      'Cloud primitives, Terraform or equivalent, state management, and cost control.',
      ['How do you manage Terraform state across a team?',
       'What happened the last time state drifted from reality?',
       'Where is your cloud spend going, and what did you cut?']],
    ['containers', 'Containers & orchestration',
      'Image hygiene, Kubernetes primitives, scheduling, resource limits.',
      ['What is in your base image that should not be?',
       'A pod is CrashLoopBackOff — walk me through it.',
       'How do you set requests and limits without guessing?']],
    ['observability', 'Observability & incidents',
      'Metrics, logs, traces, alert design, SLOs, and real incident handling.',
      ['What makes an alert worth waking someone for?',
       'Tell me about an incident you ran and what the postmortem changed.',
       'How do you trace a request across five services?']],
  ]),

  sre: plan('Site Reliability Engineer', [
    ['slo', 'SLOs & reliability targets',
      'SLI selection, error budgets, and using them to make real decisions.',
      ['How did you pick your SLIs?',
       'What happened when you burned your error budget?',
       'How do you set a target that is neither trivial nor impossible?']],
    ['incidents', 'Incident response',
      'On-call practice, triage, mitigation before diagnosis, and blameless postmortems.',
      ['Walk me through your worst page.',
       'How do you decide to mitigate before you understand the cause?',
       'What did a postmortem actually change at your company?']],
    ['observability', 'Observability',
      'Instrumentation, cardinality, tracing, and dashboards that answer questions.',
      ['What is missing from your instrumentation right now?',
       'How do you control metric cardinality?',
       'What is the first dashboard you open during an incident?']],
    ['scalability', 'Capacity & resilience',
      'Load testing, capacity planning, graceful degradation, and failure injection.',
      ['How do you plan capacity for a launch?',
       'What degrades gracefully in your system, and what does not?',
       'Have you run a game day or chaos test — what broke?']],
    ['automation', 'Toil reduction',
      'Automating operations, self-healing, and measuring toil.',
      ['What manual work did you automate away, and what did it save?',
       'Where is automation more dangerous than the manual process?',
       'How do you measure toil?']],
  ]),

  'cloud-architect': plan('Cloud Engineer / Architect', [
    ['architecture', 'Architecture design',
      'Service selection, multi-tier design, managed vs self-hosted trade-offs.',
      ['Design a highly available service on your cloud of choice — talk me through it.',
       'When do you refuse a managed service?',
       'Which architectural decision would you reverse today?']],
    ['networking', 'Networking & connectivity',
      'VPC design, subnets and routing, private connectivity, and egress control.',
      ['How do you structure VPCs and subnets for isolation?',
       'How does traffic reach a private database from your app tier?',
       'Where does your egress cost come from?']],
    ['security-iam', 'Identity & security',
      'IAM design, least privilege, secret management, encryption, and compliance.',
      ['How do you grant least privilege without blocking every team?',
       'How are secrets delivered to a running workload?',
       'What does your audit trail actually capture?']],
    ['reliability', 'Reliability & DR',
      'Multi-AZ/region strategy, backups, RTO/RPO, and tested failover.',
      ['What is your RTO and RPO, and have you tested them?',
       'Multi-region — worth it for your workload or not?',
       'When did a backup fail to restore?']],
    ['cost', 'Cost & governance',
      'Cost modelling, tagging, rightsizing, commitments, and guardrails.',
      ['How do you attribute cost to a team?',
       'What was your biggest unnecessary spend, and how did you find it?',
       'What guardrails stop someone spinning up something expensive?']],
  ]),

  'platform-engineer': plan('Platform / Infrastructure Engineer', [
    ['platform-design', 'Platform design',
      'Golden paths, abstractions, self-service, and treating internal teams as customers.',
      ['What is the golden path you built, and did teams use it?',
       'Where did your abstraction leak?',
       'How do you handle a team that wants to bypass the platform?']],
    ['kubernetes', 'Kubernetes & runtime',
      'Cluster architecture, operators/controllers, multi-tenancy, and upgrades.',
      ['How do you isolate tenants in one cluster?',
       'Walk me through a cluster upgrade with zero downtime.',
       'Have you written a controller — what did it reconcile?']],
    ['developer-experience', 'Developer experience',
      'Build/deploy ergonomics, local dev, feedback loops, and documentation.',
      ['How long from commit to running in production, and where is the time going?',
       'What does local development look like for your users?',
       'How do you know developers are unhappy before they tell you?']],
    ['reliability', 'Reliability & scale',
      'Multi-tenant reliability, noisy neighbours, quotas, and platform SLOs.',
      ['How do you stop one team degrading everyone else?',
       'What is the platform’s SLO, and who owns it?',
       'What broke when the platform grew tenfold?']],
    ['security', 'Security & policy',
      'Policy as code, supply chain, image scanning, and enforcing without blocking.',
      ['How do you enforce policy without becoming a bottleneck?',
       'How do you secure the build supply chain?',
       'What do you do about a critical CVE across 200 services?']],
  ]),

  'network-engineer': plan('Network / Systems Engineer', [
    ['fundamentals', 'Networking fundamentals',
      'TCP/IP, routing, switching, subnetting, and the OSI layers in practice.',
      ['Walk me through what happens when a packet leaves a host.',
       'How do you subnet for a growing office network?',
       'Explain a problem you solved that turned out to be MTU-related.']],
    ['routing-switching', 'Routing & switching',
      'BGP/OSPF, VLANs, spanning tree, redundancy, and convergence behaviour.',
      ['How does your network converge after a link failure?',
       'Describe a routing loop or flap you diagnosed.',
       'When do you use static routes over dynamic?']],
    ['security', 'Network security',
      'Firewalls, segmentation, VPN, ACLs, zero trust, and DDoS handling.',
      ['How do you segment a flat network you inherited?',
       'What does your firewall rule review process look like?',
       'How did you respond to a volumetric attack?']],
    ['troubleshooting', 'Troubleshooting',
      'Packet capture, latency analysis, methodical isolation, and tooling.',
      ['Users say "the network is slow" — what do you do first?',
       'What have you found in a packet capture that nothing else showed?',
       'How do you isolate a problem between the app and the network?']],
    ['operations', 'Operations & change',
      'Change management, monitoring, documentation, and maintenance windows.',
      ['How do you make a risky change safely at 2am?',
       'What do you monitor, and what alerts?',
       'Tell me about a change that went wrong.']],
  ]),

  dba: plan('Database Administrator', [
    ['architecture', 'Database architecture',
      'Engine internals, storage, replication topology, and HA design.',
      ['How is your replication set up, and what is the failover story?',
       'What does the engine do on commit?',
       'Synchronous or asynchronous replication — what did you choose and why?']],
    ['performance', 'Performance tuning',
      'Query plans, indexing strategy, statistics, locking, and configuration.',
      ['Walk me through tuning the worst query you have seen.',
       'When does adding an index make things worse?',
       'How do you diagnose lock contention?']],
    ['reliability', 'Backup & recovery',
      'Backup strategy, PITR, restore testing, RTO/RPO, and corruption handling.',
      ['Have you restored from backup under pressure — what happened?',
       'What is your point-in-time recovery capability?',
       'How would you detect silent corruption?']],
    ['operations', 'Operations & change',
      'Migrations, upgrades, capacity planning, and maintenance under load.',
      ['How do you alter a huge table without downtime?',
       'Walk me through a major version upgrade.',
       'How do you forecast storage growth?']],
    ['security', 'Security & access',
      'Privileges, encryption, auditing, and PII handling.',
      ['How do you manage privileges across environments?',
       'How is data encrypted at rest and in transit?',
       'How do you give an analyst access without exposing PII?']],
  ]),

  security: plan('Security Engineer', [
    ['appsec', 'Application security',
      'OWASP classes, secure design review, and exploit reasoning on real systems.',
      ['Walk me through finding an authorisation bug in a code review.',
       'Which OWASP category do teams most often get wrong?',
       'How would you attack a system you built?']],
    ['infra-security', 'Infrastructure & identity',
      'Network segmentation, IAM, secret management, and least privilege in practice.',
      ['How do you implement least privilege without stalling delivery?',
       'How are secrets rotated in your environment?',
       'What does lateral movement look like in your network?']],
    ['detection', 'Detection & response',
      'Logging, detection engineering, triage, and a real incident handled.',
      ['What detection have you written that actually fired on something real?',
       'Walk me through an incident from alert to closure.',
       'How do you reduce false positives without going blind?']],
    ['crypto', 'Cryptography & data protection',
      'TLS, key management, hashing vs encryption, and data-at-rest decisions.',
      ['How do you store user passwords, and why that way?',
       'Where do your keys live, and who can use them?',
       'When is encryption at rest actually not protecting you?']],
    ['governance', 'Risk & governance',
      'Threat modelling, compliance obligations, and prioritising finite effort.',
      ['How do you threat model a new feature quickly?',
       'You have 200 findings and time for 10 — how do you choose?',
       'How do you handle a risk the business decides to accept?']],
  ]),

  // =========================================================================
  // Quality / architecture / leadership / adjacent
  // =========================================================================
  'qa-sdet': plan('QA / SDET', [
    ['test-strategy', 'Test strategy',
      'Risk-based coverage, the test pyramid, and what they deliberately do not automate.',
      ['What do you refuse to automate, and why?',
       'How do you decide coverage for a feature under deadline?',
       'Where is your pyramid actually an hourglass?']],
    ['automation', 'Automation engineering',
      'Framework design, locators, waits, parallelisation, and flakiness control.',
      ['How do you eliminate flaky tests rather than retry them?',
       'How is your framework structured, and what would you change?',
       'How do you run a suite in parallel safely?']],
    ['api-data', 'API & data testing',
      'Contract testing, fixtures, mocking, and test data management.',
      ['How do you manage test data across environments?',
       'When do you mock a dependency versus use the real one?',
       'How do you test a contract between two teams?']],
    ['defects', 'Defect analysis',
      'Reproduction, triage, severity judgement, and root-cause reasoning.',
      ['A bug only reproduces in production — how do you proceed?',
       'How do you decide severity when the reporter disagrees?',
       'Tell me about a bug you found that everyone else missed.']],
    ['ci-quality', 'CI & release gates',
      'Pipeline integration, quality gates, and reporting engineers act on.',
      ['What blocks a release in your pipeline?',
       'How long is too long for a CI run, and what did you do about it?',
       'How do you report quality without producing noise?']],
  ]),

  'solutions-architect': plan('Solutions Architect', [
    ['requirements', 'Requirements & constraints',
      'Eliciting real requirements, non-functional constraints, and scoping ambiguity.',
      ['How do you get real non-functional requirements out of a customer?',
       'What constraint is most often discovered too late?',
       'How do you handle a requirement you believe is wrong?']],
    ['design', 'Architecture & trade-offs',
      'System decomposition, integration patterns, and defending a design decision.',
      ['Design a system for this scenario and justify each choice.',
       'Which trade-off do you most often have to explain to stakeholders?',
       'When did you choose the boring technology deliberately?']],
    ['integration', 'Integration & migration',
      'Legacy integration, phased migration, data movement, and cutover risk.',
      ['How do you migrate off a legacy system without a big-bang cutover?',
       'How do you keep two systems consistent during a migration?',
       'What is your rollback plan on cutover night?']],
    ['nfr', 'Reliability, security & cost',
      'Availability targets, security architecture, and cost modelling.',
      ['How do you cost a proposed architecture before building it?',
       'Where do you place security controls in this design?',
       'What does the system do when a dependency is down?']],
    ['stakeholders', 'Stakeholder influence',
      'Communicating to executives and engineers, and handling disagreement.',
      ['How do you present an architecture to a non-technical executive?',
       'Tell me about an architectural decision you lost.',
       'How do you get engineering buy-in on a design they did not write?']],
  ]),

  'engineering-manager': plan('Engineering Manager', [
    ['technical-judgement', 'Technical judgement',
      'Staying credible technically, reviewing decisions, and knowing when to intervene.',
      ['How do you stay technical enough to be useful?',
       'When did you overrule a technical decision, and was it right?',
       'How do you evaluate technical debt against feature work?']],
    ['delivery', 'Delivery & execution',
      'Planning, estimation, unblocking, and shipping under pressure.',
      ['A project is going to miss its date — what do you do and when?',
       'How do you estimate work you have not done before?',
       'How do you protect a team from thrash?']],
    ['people', 'People management',
      'Growth, feedback, performance issues, and retention.',
      ['Walk me through managing an underperformer.',
       'How do you give feedback someone does not want to hear?',
       'Who have you promoted, and what did you do to get them there?']],
    ['hiring', 'Hiring & team building',
      'Interviewing, calibration, onboarding, and team composition.',
      ['How do you calibrate your interview bar?',
       'What does your onboarding look like in week one?',
       'How do you build a team that is not all the same?']],
    ['stakeholders', 'Cross-functional leadership',
      'Working with product and other orgs, and managing upward.',
      ['How do you handle a product partner who keeps changing scope?',
       'How do you say no to your own manager?',
       'What do you escalate, and what do you absorb?']],
  ]),

  'technical-pm': plan('Technical Product Manager', [
    ['discovery', 'Discovery & problem framing',
      'Customer research, problem definition, and validating before building.',
      ['How do you validate a problem before committing engineering time?',
       'Tell me about something you decided not to build.',
       'How do you talk to users without leading them?']],
    ['technical-depth', 'Technical depth',
      'System understanding sufficient to make credible trade-off calls with engineers.',
      ['Explain the architecture of a product you owned.',
       'How do you evaluate an engineering estimate you think is inflated?',
       'What technical constraint most shaped your roadmap?']],
    ['prioritisation', 'Prioritisation & roadmap',
      'Trade-off reasoning, sequencing under constraint, and saying no.',
      ['How do you prioritise when every stakeholder is the loudest?',
       'How do you sequence platform work against visible features?',
       'What did you cut to hit a date, and what did it cost?']],
    ['metrics', 'Metrics & experimentation',
      'Success metrics, experiment design, and reading ambiguous results.',
      ['What metric defined success, and how did you pick it?',
       'Your experiment is inconclusive — what do you do?',
       'How do you avoid optimising a metric into a worse product?']],
    ['execution', 'Execution & stakeholders',
      'Working with engineering and design, scope negotiation, and shipping.',
      ['How do you handle mid-sprint scope change?',
       'Tell me about a launch that went badly.',
       'How do you keep engineers bought in on the why?']],
  ]),

  'support-engineer': plan('Technical Support Engineer', [
    ['technical-depth', 'Technical depth',
      'Product internals, logs, APIs, and enough systems knowledge to diagnose properly.',
      ['How deep can you go before you escalate?',
       'What do you look for in a log first?',
       'Walk me through debugging a failing API integration for a customer.']],
    ['troubleshooting', 'Troubleshooting method',
      'Systematic isolation on an ambiguous report, and reproduction discipline.',
      ['A customer says "it is broken" with no details — what do you ask?',
       'How do you reproduce an issue you cannot see?',
       'When do you conclude it is not your product?']],
    ['communication', 'Customer communication',
      'De-escalation, explaining causes plainly, and managing expectations.',
      ['How do you tell a customer their data is not recoverable?',
       'How do you explain a root cause without jargon?',
       'How do you handle an angry escalation from an executive?']],
    ['process', 'Process & tooling',
      'Triage, SLAs, escalation paths, documentation, and knowledge base.',
      ['When do you escalate to engineering, and what do you include?',
       'How do you keep a knowledge base from rotting?',
       'How do you handle an SLA you are about to breach?']],
    ['impact', 'Feedback loop',
      'Turning support signal into product improvement.',
      ['What recurring issue did you get permanently fixed?',
       'How do you quantify the cost of a bug to support?',
       'What do you tell product that they do not want to hear?']],
  ]),

  'ux-designer': plan('UI / UX Designer', [
    ['process', 'Process & research',
      'Going from a vague problem to a validated direction, and research methods.',
      ['How did you get from a vague brief to a direction you trusted?',
       'What research method do you use when there is no budget?',
       'When did research contradict your instinct?']],
    ['craft', 'Interaction & visual craft',
      'Layout, hierarchy, typography, states, and edge cases in their own work.',
      ['Walk me through the empty, loading, and error states of a screen you designed.',
       'How do you establish hierarchy on a dense screen?',
       'What in your portfolio would you redo?']],
    ['design-systems', 'Design systems',
      'Component and token thinking, consistency, and scaling across teams.',
      ['How do you decide something belongs in the system?',
       'How do you handle a team that keeps going off-system?',
       'How do you version a breaking component change?']],
    ['collaboration', 'Collaboration & handoff',
      'Working with engineering, handling critique, and defending decisions with evidence.',
      ['How do you hand off so engineers do not have to guess?',
       'Tell me about design feedback you disagreed with.',
       'What do you do when engineering says it is too expensive to build?']],
    ['impact', 'Outcomes',
      'What measurably changed after the design shipped.',
      ['What metric moved because of your design?',
       'How do you know a redesign worked?',
       'What shipped and then failed?']],
  ]),

  // =========================================================================
  // Non-technical
  // =========================================================================
  hr: plan('HR / People Operations', [
    ['talent-acquisition', 'Talent acquisition',
      'Sourcing strategy, pipeline management, interview process design, time-to-hire trade-offs.',
      ['How do you fill a role nobody wants to apply to?',
       'How do you know your interview process is not just filtering for confidence?',
       'What is your time-to-hire, and what slows it down?']],
    ['employee-relations', 'Employee relations',
      'Grievances, conflict mediation, performance management, and a real case owned.',
      ['Walk me through a grievance you handled end to end.',
       'How do you mediate between a manager and their report?',
       'When did you have to act against a manager’s wishes?']],
    ['policy-compliance', 'Policy & compliance',
      'Labour law exposure, documentation discipline, terminations, confidentiality.',
      ['How do you document a performance issue so it holds up?',
       'Walk me through a termination you managed.',
       'How do you handle a policy the business keeps ignoring?']],
    ['compensation', 'Compensation & benefits',
      'Banding, benchmarking, equity and benefits structure, counter-offers.',
      ['How do you handle a counter-offer from a competitor?',
       'How do you fix a pay-equity problem you discover?',
       'How do you explain a band to someone who thinks they are underpaid?']],
    ['people-analytics', 'People analytics',
      'Attrition and engagement metrics, and what changed as a result.',
      ['What did your attrition data actually tell you?',
       'How do you measure whether engagement work worked?',
       'What people metric do you distrust?']],
  ]),

  'business-development': plan('Business Development', [
    ['market-research', 'Market & targeting',
      'Segmentation, opportunity sizing, and account selection.',
      ['How did you decide which segment to attack first?',
       'How do you size an opportunity you have no data on?',
       'Which accounts did you deliberately walk away from?']],
    ['lead-generation', 'Lead generation & outreach',
      'Channel mix, outreach messaging, qualification criteria, conversion rates.',
      ['What is your reply rate, and what changed it?',
       'How do you qualify out fast?',
       'Which channel worked and which one wasted your quarter?']],
    ['pitching', 'Pitching & discovery',
      'Discovery questioning, value articulation, and tailoring to a buyer.',
      ['What do you ask in the first ten minutes of a discovery call?',
       'How do you pitch differently to a CFO versus an operator?',
       'How do you handle a prospect who will not tell you their budget?']],
    ['negotiation', 'Negotiation & closing',
      'Objection handling, pricing and concession strategy, and losses.',
      ['Walk me through your biggest lost deal and why you lost it.',
       'What do you concede, and what never moves?',
       'How do you handle procurement pushing on price at the last minute?']],
    ['partnerships', 'Partnerships & metrics',
      'Account growth, partner management, pipeline hygiene, and the numbers owned.',
      ['What number were you held to, and did you hit it?',
       'How do you keep a partnership alive after the launch press release?',
       'How do you keep your pipeline honest?']],
  ]),

  sales: plan('Sales', [
    ['prospecting', 'Prospecting',
      'Territory planning, outreach cadence, and pipeline generation discipline.',
      ['What does your week look like when the pipeline is thin?',
       'What is your cadence, and why that shape?',
       'How much pipeline do you need to hit quota?']],
    ['discovery', 'Discovery & qualification',
      'Qualification framework, uncovering real pain, and disqualifying early.',
      ['How do you tell real pain from polite interest?',
       'What is your qualification framework, and where does it fail?',
       'When did you disqualify a deal your manager wanted?']],
    ['objections', 'Objection handling',
      'Pricing pushback, competitor comparisons, and stalled deals.',
      ['"You are too expensive" — what do you actually say?',
       'How do you handle a deal that has gone quiet for three weeks?',
       'How do you compete against an incumbent?']],
    ['closing', 'Closing',
      'Multi-threading, procurement and legal navigation, close plans.',
      ['How many people did you have to win over in your biggest deal?',
       'What is in your close plan?',
       'What do you do when your champion leaves?']],
    ['forecasting', 'Forecasting & CRM',
      'Quota attainment, forecast accuracy, and pipeline hygiene.',
      ['How accurate was your forecast, and how do you know?',
       'What makes you move a deal to commit?',
       'How do you keep CRM data honest when it is not fun?']],
  ]),

  product: plan('Product Manager', [
    ['discovery', 'Discovery & research',
      'Problem framing, user research, and validating before building.',
      ['How do you validate a problem is worth solving?',
       'Tell me about something you killed after research.',
       'How do you research when you cannot reach users?']],
    ['prioritisation', 'Prioritisation & roadmap',
      'Trade-off reasoning, saying no, and sequencing under constraint.',
      ['How do you prioritise between two teams who both need you?',
       'How do you say no to a founder?',
       'What is on your roadmap that should not be?']],
    ['metrics', 'Metrics & experimentation',
      'Success metrics, experiment design, and reading ambiguous results.',
      ['What metric did you own, and did it move?',
       'How do you design an experiment for a low-traffic product?',
       'When did a metric mislead you?']],
    ['execution', 'Execution & stakeholders',
      'Working with engineering and design, scope negotiation, shipping under pressure.',
      ['How do you handle scope creep mid-sprint?',
       'Tell me about a launch that failed.',
       'How do you keep the team aligned on the why?']],
    ['technical-fluency', 'Technical fluency',
      'Enough system understanding to make credible trade-off calls with engineers.',
      ['Explain how the product you owned actually works.',
       'How do you evaluate a build-versus-buy decision?',
       'When did a technical constraint change your plan?']],
  ]),

  marketing: plan('Marketing', [
    ['positioning', 'Positioning & messaging',
      'Audience definition, differentiation, and message testing.',
      ['How did you position against a better-known competitor?',
       'How do you test a message before spending on it?',
       'Who is explicitly not your audience?']],
    ['channels', 'Channels & campaigns',
      'Channel selection, budget allocation, and campaign execution.',
      ['How do you split a fixed budget across channels?',
       'Which channel did you kill, and why?',
       'Walk me through a campaign from brief to results.']],
    ['content', 'Content & brand',
      'Content strategy, production process, and brand consistency.',
      ['How do you produce content consistently without a big team?',
       'How do you know content is working?',
       'How do you keep brand consistent across contributors?']],
    ['analytics', 'Analytics & attribution',
      'Funnel metrics, attribution limits, CAC/LTV reasoning.',
      ['What is your CAC, and how do you actually calculate it?',
       'Where does your attribution model lie to you?',
       'Which funnel stage was your real bottleneck?']],
    ['growth', 'Growth experiments',
      'A specific experiment run, the hypothesis, and the outcome.',
      ['Tell me about an experiment that failed and what you learned.',
       'How do you prioritise growth experiments?',
       'What is the biggest lift you have driven?']],
  ]),

  finance: plan('Finance / Accounting', [
    ['accounting', 'Accounting fundamentals',
      'The three statements, accruals, and how a transaction flows through them.',
      ['Walk a transaction through all three statements.',
       'Explain the difference between profit and cash to a non-finance person.',
       'What accrual judgement have you had to defend?']],
    ['analysis', 'Financial analysis',
      'Variance analysis, unit economics, and the drivers behind a number.',
      ['Margin dropped two points — how do you find out why?',
       'What are the unit economics of a business you supported?',
       'What number did leadership misunderstand, and how did you fix it?']],
    ['modelling', 'Modelling & forecasting',
      'Model structure, assumption discipline, and sensitivity analysis.',
      ['How do you structure a model so someone else can audit it?',
       'Which assumption drives your model most, and how do you sanity check it?',
       'How wrong was your last forecast?']],
    ['controls', 'Controls & compliance',
      'Close process, reconciliation, audit readiness, and regulatory exposure.',
      ['How do you shorten a month-end close?',
       'What control gap have you found and closed?',
       'Walk me through preparing for an audit.']],
    ['partnering', 'Business partnering',
      'Influencing a non-finance decision with a financial argument.',
      ['Tell me about a time you changed a business decision with analysis.',
       'How do you say no to a budget request?',
       'How do you make finance useful rather than bureaucratic?']],
  ]),

  support: plan('Customer Support / Success', [
    ['product-knowledge', 'Product knowledge',
      'Depth on the product supported and how they got up to speed.',
      ['How did you learn the product fast enough to be useful?',
       'What is the hardest thing to explain about it?',
       'How do you stay current as it changes?']],
    ['troubleshooting', 'Troubleshooting',
      'Diagnostic method on an ambiguous report, and escalation judgement.',
      ['How do you narrow down a vague complaint?',
       'When do you escalate, and what do you send with it?',
       'Tell me about a problem you solved that engineering could not reproduce.']],
    ['communication', 'Customer communication',
      'De-escalation and explaining a technical cause plainly.',
      ['How do you calm a furious customer?',
       'How do you deliver bad news you cannot fix?',
       'How do you say no while keeping the relationship?']],
    ['process', 'Process & tooling',
      'Ticket triage, SLAs, macros and knowledge base, CRM discipline.',
      ['How do you triage a queue that is on fire?',
       'What did you automate or templatise?',
       'How do you balance speed against quality of response?']],
    ['retention', 'Retention & metrics',
      'CSAT/churn ownership and a save or renewal personally driven.',
      ['Tell me about an account you saved.',
       'What early signal tells you an account is about to churn?',
       'What metric were you measured on, and did you hit it?']],
  ]),

  generic: plan('General', [
    ['background', 'Background & scope',
      'Actual scope of ownership, team shape, and what they personally did.',
      ['What did you personally own versus what the team owned?',
       'Walk me through your last project end to end.',
       'What would your manager say you are best at?']],
    ['core-skills', 'Core domain skills',
      'The primary tools, methods, and domain knowledge claimed on the resume.',
      ['Pick the strongest skill on your resume and go deep on it.',
       'What is on your resume that you would not claim to be expert in?',
       'How did you learn it?']],
    ['problem-solving', 'Problem solving',
      'A hard problem from their history, their method, and the trade-offs weighed.',
      ['Tell me about the hardest problem you have solved.',
       'What did you try that did not work?',
       'What would you do differently now?']],
    ['collaboration', 'Collaboration & ownership',
      'Conflict, stakeholder management, and owning a bad outcome.',
      ['Tell me about a disagreement with a colleague and how it ended.',
       'When did something fail on your watch?',
       'How do you work with someone you find difficult?']],
    ['role-fit', 'Role fit',
      'Gaps between their background and the target role, pressure-tested directly.',
      ['What is the biggest gap between your experience and this role?',
       'Why this role, specifically?',
       'What would make you fail here?']],
  ]),
};

/**
 * Keyword signals per role family. An explicit target role weighs far more than
 * a passing resume mention, and broader families (fullstack) are weighted above
 * the narrower ones so "full stack" is not shredded into one half.
 */
const SIGNALS: { key: RoleKey; terms: string[]; weight?: number }[] = [
  { key: 'fullstack', terms: ['full stack', 'fullstack', 'full-stack', 'mern', 'mean stack'], weight: 4 },

  { key: 'prompt-engineer', terms: ['prompt engineer', 'ai application', 'genai engineer', 'llm application'], weight: 4 },
  { key: 'computer-vision', terms: ['computer vision', 'image segmentation', 'object detection', 'opencv'], weight: 4 },
  { key: 'nlp', terms: ['nlp engineer', 'natural language processing', 'text mining', 'speech recognition'], weight: 4 },
  { key: 'mlops', terms: ['mlops', 'ml platform', 'model serving', 'ml infrastructure', 'kubeflow', 'mlflow'], weight: 4 },
  { key: 'ai-engineer', terms: ['machine learning', 'ml engineer', 'ai engineer', 'deep learning', 'llm', 'pytorch', 'tensorflow', 'hugging face', 'rag', 'generative ai'], weight: 3 },

  { key: 'data-engineer', terms: ['data engineer', 'etl', 'elt', 'airflow', 'dbt', 'spark', 'data pipeline', 'warehouse'], weight: 3 },
  { key: 'data-scientist', terms: ['data scientist', 'statistical model', 'experimentation', 'a/b testing', 'causal inference'], weight: 3 },
  { key: 'bi-developer', terms: ['business intelligence', 'bi developer', 'power bi', 'tableau', 'looker', 'qlik', 'dax'], weight: 3 },
  { key: 'data-analyst', terms: ['data analyst', 'business analyst', 'analytics', 'reporting analyst'], weight: 2 },

  { key: 'sre', terms: ['site reliability', 'sre', 'error budget', 'slo'], weight: 4 },
  { key: 'platform-engineer', terms: ['platform engineer', 'internal developer platform', 'developer experience', 'infrastructure engineer'], weight: 4 },
  { key: 'cloud-architect', terms: ['cloud architect', 'cloud engineer', 'solutions architect aws', 'azure architect', 'gcp architect'], weight: 4 },
  { key: 'devops', terms: ['devops', 'kubernetes', 'terraform', 'ci/cd', 'jenkins', 'ansible'], weight: 3 },
  { key: 'network-engineer', terms: ['network engineer', 'systems administrator', 'sysadmin', 'ccna', 'bgp', 'ospf'], weight: 3 },
  { key: 'dba', terms: ['database administrator', 'dba', 'oracle dba', 'postgres administration', 'sql server administration'], weight: 4 },
  { key: 'security', terms: ['security engineer', 'cybersecurity', 'appsec', 'penetration test', 'soc analyst', 'infosec'], weight: 3 },

  { key: 'mobile-ios', terms: ['ios developer', 'ios engineer', 'swift', 'swiftui', 'objective-c'], weight: 3 },
  { key: 'mobile-android', terms: ['android developer', 'android engineer', 'kotlin', 'jetpack compose'], weight: 3 },
  { key: 'embedded', terms: ['embedded', 'firmware', 'rtos', 'microcontroller', 'bare metal', 'stm32'], weight: 4 },
  { key: 'game-dev', terms: ['game developer', 'unity', 'unreal engine', 'game programmer', 'gameplay engineer'], weight: 4 },
  { key: 'blockchain', terms: ['blockchain', 'solidity', 'smart contract', 'web3', 'ethereum'], weight: 4 },
  { key: 'salesforce-developer', terms: ['salesforce', 'apex', 'lightning web component', 'crm developer'], weight: 4 },

  { key: 'qa-sdet', terms: ['qa engineer', 'test engineer', 'sdet', 'quality assurance', 'automation tester', 'selenium', 'cypress'], weight: 3 },
  { key: 'solutions-architect', terms: ['solutions architect', 'enterprise architect', 'technical architect'], weight: 3 },
  { key: 'engineering-manager', terms: ['engineering manager', 'tech lead manager', 'head of engineering', 'director of engineering'], weight: 4 },
  { key: 'technical-pm', terms: ['technical product manager', 'tpm', 'platform product manager'], weight: 4 },
  { key: 'support-engineer', terms: ['support engineer', 'technical support', 'solutions engineer', 'sales engineer'], weight: 3 },
  { key: 'ux-designer', terms: ['ux designer', 'ui designer', 'product designer', 'figma', 'interaction design'], weight: 3 },

  { key: 'frontend', terms: ['frontend', 'front end', 'front-end', 'react', 'vue', 'angular', 'ui engineer'] },
  { key: 'backend', terms: ['backend', 'back end', 'back-end', 'api developer', 'microservices', 'django', 'spring boot', 'node.js'] },

  {
    key: 'hr',
    // ' hr ' is space-padded on purpose: role/body text is padded too, so this
    // catches "HR Business Partner" without matching inside unrelated words.
    terms: ['human resource', 'hrbp', ' hr ', 'hr business partner', 'hr generalist', 'hr manager',
      'people operations', 'talent acquisition', 'recruiter', 'recruitment'],
    weight: 4,
  },
  { key: 'business-development', terms: ['business development', 'bd manager', 'bdm', 'partnerships', 'client acquisition'], weight: 4 },
  { key: 'sales', terms: ['account executive', 'inside sales', 'sales development', 'quota', 'sales manager'], weight: 3 },
  { key: 'product', terms: ['product manager', 'product owner', 'roadmap', 'product management'], weight: 3 },
  { key: 'marketing', terms: ['marketing', 'seo', 'content strategist', 'demand generation', 'brand manager'], weight: 2 },
  { key: 'finance', terms: ['accountant', 'financial analyst', 'finance manager', 'cpa', 'bookkeep', 'auditor'], weight: 2 },
  { key: 'support', terms: ['customer support', 'customer success', 'help desk', 'account manager'], weight: 2 },
];

/**
 * Pick a plan from the static library. The target role is the strongest signal;
 * resume and JD text act as weaker corroboration.
 */
export function detectRolePlan(input: {
  role?: string;
  jd?: string;
  resume?: string;
}): InterviewPlan {
  const roleText = ` ${(input.role ?? '').toLowerCase()} `;
  const bodyText = ` ${(input.jd ?? '').toLowerCase()} ${(input.resume ?? '').toLowerCase()} `;

  let best: { key: RoleKey; score: number } | null = null;

  for (const signal of SIGNALS) {
    const weight = signal.weight ?? 1;
    let score = 0;
    for (const term of signal.terms) {
      if (roleText.includes(term)) score += 10 * weight;
      else if (bodyText.includes(term)) score += weight;
    }
    if (score > 0 && (!best || score > best.score)) {
      best = { key: signal.key, score };
    }
  }

  return PLANS[best?.key ?? 'generic'];
}

/** Every plan in the library, for docs/tests. */
export function allRolePlans(): InterviewPlan[] {
  return Object.values(PLANS);
}

function cleanString(value: unknown, max: number): string {
  return typeof value === 'string' ? value.trim().slice(0, max) : '';
}

function slugify(value: string, fallback: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || fallback;
}

/**
 * Validate a model-generated plan. Returns null when the shape is unusable so
 * the caller can fall back to the static library.
 */
export function normalizePlan(raw: unknown): InterviewPlan | null {
  if (!raw || typeof raw !== 'object') return null;
  const candidate = raw as { roleFamily?: unknown; areas?: unknown };
  if (!Array.isArray(candidate.areas)) return null;

  const seen = new Set<string>();
  const areas: InterviewArea[] = [];

  for (const item of candidate.areas) {
    if (!item || typeof item !== 'object') continue;
    const entry = item as { key?: unknown; title?: unknown; focus?: unknown; probes?: unknown };
    const title = cleanString(entry.title, 40);
    const focus = cleanString(entry.focus, 400);
    if (!title || !focus) continue;

    const key = slugify(cleanString(entry.key, 40) || title, `area-${areas.length + 1}`);
    if (seen.has(key)) continue;
    seen.add(key);

    const probes = Array.isArray(entry.probes)
      ? entry.probes.map((p) => cleanString(p, 200)).filter(Boolean).slice(0, 4)
      : undefined;

    areas.push({ key, title, focus, ...(probes?.length ? { probes } : {}) });
    if (areas.length === MAX_AREAS) break;
  }

  if (areas.length < MIN_AREAS) return null;

  return {
    roleFamily: cleanString(candidate.roleFamily, 60) || 'General',
    areas,
  };
}
